apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: docker-sync
  namespace: docker-sync

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: docker-sync
  managed-by: kustomize

images:
  - name: docker-image-sync
    newTag: latest

replicas:
  - name: docker-sync
    count: 1

configMapGenerator:
  - name: docker-sync-env
    literals:
      - ENVIRONMENT=production
      - VERSION=v1.0.0

secretGenerator:
  - name: docker-sync-secrets
    literals:
      - DATABASE_URL=placeholder

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: docker-sync
      namespace: docker-sync
    spec:
      template:
        metadata:
          annotations:
            config/checksum: placeholder 