apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-sync-logs
  namespace: docker-sync
  labels:
    app: docker-sync
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-sync-downloads
  namespace: docker-sync
  labels:
    app: docker-sync
    component: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 