apiVersion: v1
kind: Secret
metadata:
  name: docker-sync-secret
  namespace: docker-sync
  labels:
    app: docker-sync
type: Opaque
data:
  # Base64编码的用户配置
  # 使用: echo -n "your-value" | base64
  # 请将 config/users.yaml.example 的内容编码后填入
  users.yaml: |
    # 请替换为实际的base64编码的用户配置
    # 生成方法:
    # cat config/users.yaml | base64 -w 0
    <BASE64_ENCODED_USERS_CONFIG>
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: docker-sync
  labels:
    app: docker-sync
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    # Base64编码的Docker配置
    # 格式: {"auths":{"registry-url":{"username":"user","password":"pass","auth":"base64(user:pass)"}}}
    # 生成方法:
    # echo -n '{"auths":{"your-registry.com":{"username":"user","password":"pass","auth":"dXNlcjpwYXNz"}}}' | base64 -w 0
    <BASE64_ENCODED_DOCKER_CONFIG> 